### ISSUE TITLE
Approvazione project plan

### ISSUE THREAD

**Issue by Ombuman** [Ombuman/IS22#6]
Professor @Garganti le chiediamo l'approvazione del project plan
Cordali saluti,
Andrea, Gabriele, Marco e Romeo

**Comment by garganti** [comment]
- mettete anche il doc su github
- non ho capito come si mappano i moduli, per ora vedo solo il progetto vaadin che mi sembra sia il backend .. forse però devo generare il codice? Tutto nello stesso progetto? va bene anche così però attenti ai packages.
approvato
